/*
 * This file is generated by jOOQ.
*/
package com.imos.sample.model;


import com.imos.sample.model.tables.Address;
import com.imos.sample.model.tables.Author;
import com.imos.sample.model.tables.Book;
import com.imos.sample.model.tables.FlywaySchemaHistory;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Library extends SchemaImpl {

    private static final long serialVersionUID = 250995568;

    /**
     * The reference instance of <code>library</code>
     */
    public static final Library LIBRARY = new Library();

    /**
     * The table <code>library.address</code>.
     */
    public final Address ADDRESS = com.imos.sample.model.tables.Address.ADDRESS;

    /**
     * The table <code>library.author</code>.
     */
    public final Author AUTHOR = com.imos.sample.model.tables.Author.AUTHOR;

    /**
     * The table <code>library.book</code>.
     */
    public final Book BOOK = com.imos.sample.model.tables.Book.BOOK;

    /**
     * The table <code>library.flyway_schema_history</code>.
     */
    public final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.imos.sample.model.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * No further instances allowed
     */
    private Library() {
        super("library", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Author.AUTHOR,
            Book.BOOK,
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY);
    }
}
