/*
 * This file is generated by jOOQ.
*/
package com.imos.sample.model;


import com.imos.sample.model.tables.Address;
import com.imos.sample.model.tables.Author;
import com.imos.sample.model.tables.Book;
import com.imos.sample.model.tables.FlywaySchemaHistory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in library
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>library.address</code>.
     */
    public static final Address ADDRESS = com.imos.sample.model.tables.Address.ADDRESS;

    /**
     * The table <code>library.author</code>.
     */
    public static final Author AUTHOR = com.imos.sample.model.tables.Author.AUTHOR;

    /**
     * The table <code>library.book</code>.
     */
    public static final Book BOOK = com.imos.sample.model.tables.Book.BOOK;

    /**
     * The table <code>library.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = com.imos.sample.model.tables.FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;
}
