/*
 * This file is generated by jOOQ.
*/
package com.imos.sample.model.tables.records;


import com.imos.sample.model.tables.Book;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BookRecord extends UpdatableRecordImpl<BookRecord> implements Record8<Integer, String, String, String, Date, String, String, Integer> {

    private static final long serialVersionUID = 811140644;

    /**
     * Setter for <code>library.book.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>library.book.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>library.book.title</code>.
     */
    public void setTitle(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>library.book.title</code>.
     */
    public String getTitle() {
        return (String) get(1);
    }

    /**
     * Setter for <code>library.book.description</code>.
     */
    public void setDescription(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>library.book.description</code>.
     */
    public String getDescription() {
        return (String) get(2);
    }

    /**
     * Setter for <code>library.book.language</code>.
     */
    public void setLanguage(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>library.book.language</code>.
     */
    public String getLanguage() {
        return (String) get(3);
    }

    /**
     * Setter for <code>library.book.year_of_edition</code>.
     */
    public void setYearOfEdition(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>library.book.year_of_edition</code>.
     */
    public Date getYearOfEdition() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>library.book.type_of_book</code>.
     */
    public void setTypeOfBook(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>library.book.type_of_book</code>.
     */
    public String getTypeOfBook() {
        return (String) get(5);
    }

    /**
     * Setter for <code>library.book.domain</code>.
     */
    public void setDomain(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>library.book.domain</code>.
     */
    public String getDomain() {
        return (String) get(6);
    }

    /**
     * Setter for <code>library.book.author_id</code>.
     */
    public void setAuthorId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>library.book.author_id</code>.
     */
    public Integer getAuthorId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Date, String, String, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, String, Date, String, String, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Book.BOOK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Book.BOOK.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Book.BOOK.DESCRIPTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Book.BOOK.LANGUAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Book.BOOK.YEAR_OF_EDITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Book.BOOK.TYPE_OF_BOOK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Book.BOOK.DOMAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Book.BOOK.AUTHOR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getYearOfEdition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getTypeOfBook();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getDescription();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLanguage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getYearOfEdition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getTypeOfBook();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getDomain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getAuthorId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value2(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value3(String value) {
        setDescription(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value4(String value) {
        setLanguage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value5(Date value) {
        setYearOfEdition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value6(String value) {
        setTypeOfBook(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value7(String value) {
        setDomain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord value8(Integer value) {
        setAuthorId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BookRecord values(Integer value1, String value2, String value3, String value4, Date value5, String value6, String value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BookRecord
     */
    public BookRecord() {
        super(Book.BOOK);
    }

    /**
     * Create a detached, initialised BookRecord
     */
    public BookRecord(Integer id, String title, String description, String language, Date yearOfEdition, String typeOfBook, String domain, Integer authorId) {
        super(Book.BOOK);

        set(0, id);
        set(1, title);
        set(2, description);
        set(3, language);
        set(4, yearOfEdition);
        set(5, typeOfBook);
        set(6, domain);
        set(7, authorId);
    }
}
